### ISSUE TITLE
Remove read more button at the bottom of post

### ISSUE THREAD

**Issue by Moro-Code** [DIS-SIN/Ghost#12]
- [x] confirm with product team it's the button that needs to be removed
- [x] action what is requred

**Comment by Jordan-Morrison** [comment]
Reached out to the design team to confirm the button that needs to be removed 
<img width="904" alt="Screen Shot 2019-10-15 at 2 30 31 PM" src="https://user-images.githubusercontent.com/32398038/66859110-a5d6f780-ef58-11e9-8400-eca127f79593.png">

**Comment by Jordan-Morrison** [comment]
https://github.com/DIS-SIN/Ghost/commit/2d45b2e4fd0ea8bc432b0dbc6287a6ed0ae3abb5
