### ISSUE TITLE
Add beta to header

### ISSUE THREAD

**Issue by Moro-Code** [DIS-SIN/Ghost#14]
- [x] Find out where to add the beta
- [x] Find out beta text in French and English
- [x] add beta

**Comment by Jordan-Morrison** [comment]
Reached out to design team on where the "beta" label should go

**Comment by Jordan-Morrison** [comment]
Found out where they want the text, just waiting on the text itself
![image](https://user-images.githubusercontent.com/32398038/66863755-b5a70980-ef61-11e9-8e86-8203b162dd52.png)

**Comment by Moro-Code** [comment]
Updated design 
![beta-message](https://user-images.githubusercontent.com/26819992/67218357-406d8580-f3f4-11e9-8ed8-d489655b1edf.png)

https://invis.io/JZUFCQQVUYG#/389530630_Dark_Feedback_Closed

Focus only on banner for beta 

https://docs.google.com/document/d/1ZC7jK32fllnhE9R3ij1EQt0oIZIODLK11AUIkSliK-w/edit?usp=sharing

**Comment by Jordan-Morrison** [comment]
#22
